site_name: LinuxGateway Command
pages:
    - Home: index.md
    - UDPCommand: UDP_Command.md
    - IRCOMMAND:
      - aaaa: IR_command1.md
      - 2222: IR_command2.md
theme: 'slate'
#theme: readthedocs
# Extensions
#markdown_extensions:
#  - codehilite(css_class=code)
#  - admonition

